### ISSUE TITLE
Add License Agreement

### ISSUE THREAD

**Issue by Dante83** [nitinsurana/jsPlumb-Persistence#1]
@nitinsurana Would you be so kind as to add license to this project (MIT, Apache, etc.) Having no license limits people from using your code in any way, be that commercial or personal. 

For more information see:
[https://choosealicense.com/no-permission/](https://choosealicense.com/no-permission/)
and
[github/choosealicense.com#196](github/choosealicense.com#196)

Thank you,
Dante

**Comment by nitinsurana** [comment]
Done. Thanks @Dante83 for reporting it.

https://github.com/nitinsurana/jsPlumb-Persistence/commit/9703d50fc5db294c3f22fa4ea75d20aa517e21aa
